# Generated by Django 6.0 on 2026-01-11 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50, verbose_name='نوع الخدمة')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة')),
                ('details', models.TextField(blank=True, verbose_name='تفاصيل إضافية')),
                ('document', models.FileField(upload_to='legal_docs/', verbose_name='ملف العقد')),
                ('ai_report', models.TextField(blank=True, null=True, verbose_name='تقرير الذكاء الاصطناعي')),
                ('final_document', models.FileField(blank=True, null=True, upload_to='final_docs/', verbose_name='الوثيقة النهائية المعدلة')),
                ('status', models.CharField(choices=[('pending_review', 'قيد المراجعة الأولية'), ('awaiting_deposit', 'انتظار سداد جدية الطلب (10$)'), ('processing', 'جاري المعالجة والتدقيق'), ('supervisor_review', 'مراجعة المشرف النهائية'), ('completed', 'اكتملت المعالجة - جاهز للاستلام')], default='pending_review', max_length=30, verbose_name='حالة الطلب')),
                ('is_deposit_paid', models.BooleanField(default=False, verbose_name='تم سداد الجدية')),
                ('total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الرسم النهائي الكلي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
