# Generated by Django 6.0 on 2026-01-11 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المرجع')),
                ('ref_type', models.CharField(choices=[('law', 'قانون/تشريع'), ('precedent', 'سابقة قضائية'), ('template', 'نموذج عقد قياسي'), ('article', 'دراسة قانونية')], max_length=20, verbose_name='نوع المرجع')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة/الاختصاص')),
                ('content', models.TextField(verbose_name='النص القانوني')),
                ('tags', models.CharField(help_text='كلمات مفتاحية', max_length=255, verbose_name='وسوم')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='رابط المصدر')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='legal_library/', verbose_name='ملف المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مرجع قانوني',
                'verbose_name_plural': 'المكتبة القانونية',
            },
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='ai_report',
            field=models.TextField(blank=True, null=True, verbose_name='تقرير AI'),
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل إضافية'),
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='document',
            field=models.FileField(upload_to='legal_docs/', verbose_name='العقد/الوثيقة'),
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='final_document',
            field=models.FileField(blank=True, null=True, upload_to='final_docs/', verbose_name='الوثيقة النهائية'),
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='service_type',
            field=models.CharField(choices=[('audit', 'تدقيق وتطهير'), ('engineer', 'هندسة وصياغة'), ('protect', 'تحصين وحماية')], max_length=20, verbose_name='نوع الخدمة'),
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='status',
            field=models.CharField(choices=[('pending_review', 'قيد المراجعة'), ('awaiting_deposit', 'انتظار سداد الجدية'), ('processing', 'جاري المعالجة'), ('supervisor_review', 'مراجعة المشرف'), ('completed', 'اكتملت')], default='pending_review', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='إجمالي الرسوم'),
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
    ]
