# Generated by Django 6.0 on 2026-01-11 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_core', '0002_legalreference_alter_legalrequest_ai_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalreference',
            options={},
        ),
        migrations.RemoveField(
            model_name='legalreference',
            name='ref_type',
        ),
        migrations.RemoveField(
            model_name='legalreference',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='legalrequest',
            name='final_document',
        ),
        migrations.RemoveField(
            model_name='legalrequest',
            name='is_deposit_paid',
        ),
        migrations.RemoveField(
            model_name='legalrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='legalrequest',
            name='total_fee',
        ),
        migrations.AlterField(
            model_name='legalreference',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='laws/'),
        ),
        migrations.AlterField(
            model_name='legalreference',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='legalreference',
            name='country',
            field=models.CharField(choices=[('SA', 'السعودية'), ('EG', 'مصر'), ('AE', 'الإمارات')], max_length=2),
        ),
        migrations.AlterField(
            model_name='legalreference',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='legalreference',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='ai_report',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='country',
            field=models.CharField(default='SA', max_length=50),
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل الطلب'),
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='service_type',
            field=models.CharField(choices=[('audit', 'تدقيق العقود'), ('engineer', 'هندسة العقود'), ('protect', 'الحماية القانونية')], max_length=20),
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, max_length=100, verbose_name='اسم المكتب')),
                ('firm_logo', models.ImageField(blank=True, null=True, upload_to='firm_logos/', verbose_name='شعار المكتب')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
